### ISSUE TITLE
Does LoStik work with Android?

### ISSUE THREAD

**Issue by DimaBond174** [ronoth/LoStik#13]
Hi

Can i connect LoStik device to Android phone and work with them through OTG?
Will it work for Android 8, 9 (API > 24)?
Is the power supply from the phone's OTG enough for  to work the LoStik?

Thanks in advance for the answers..

**Comment by lolsborn** [comment]
I don’t know anyone who has tried with Android. It is a serial text device using a CH340 usb to serial converter. It works with other flavors of Linux including Raspian, but I don’t currently have an Android device to test on.

**Comment by lolsborn** [comment]
This app claims to support FTDI and CH340G devices so it seems like it's a possibility. https://play.google.com/store/apps/details?id=com.liorhass.android.usbterminal.free&hl=en_US
