### ISSUE TITLE
How to send string data in lorawan.py

### ISSUE THREAD

**Issue by aditya767** [ronoth/LoStik#21]
protocol.send_cmd("mac tx uncnf 1 hgbhbjbhjbbjyjbv")

This gives invalid_param. How to pass string?
I also tried :
protocol.send_cmd("mac tx uncnf 1 %s" % "fsdfdssdvdvs")
but it also gives invalid_param.
Please help.
Also what is the max size of string(payload) I can send?

**Comment by lolsborn** [comment]
The data has to be converted to hex. Take a look at the command reference linked in the README.  

```
<data> hexadecimal value.
The length of <data> bytes capable of being transmitted are dependent upon the set
data rate (please refer to the LoRaWAN™ Specification for further details
```
